#!/bin/bash
###############################################################################
# Copyright (C) 2013, Frank Sauerburger
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
###############################################################################

# Must be run as root.

# packages
echo "=== Installing Packages... ==="
apt-get -y install python3 ipython3 python3 python3-mathplotlib python3-scipy python3-numpy jabref guake wakeonlan cifs-utils texlive-full

# vimbin/ & tmux
echo "=== Copying Program Configs ==="
cp .vimrc ~
cp .tmux.conf ~

echo "=== Installing Tools  ==="
# qlatex
cp bin/qlatex /usr/bin
chmod +x /usr/bin/qlatex
cp .qlatex.tex ~

# qletter
cp bin/qletter /usr/bin
chmod +x /usr/bin/qletter
cp .qletter.tex ~

# toolbox
cp bin/t /usr/bin
chmod +x /usr/bin/t
cp ttemplate/tex/* /usr/share/ttemplate/tex
