#!/usr/bin/env python3
##############################################################################
#
#       Quick Latex
#
##############################################################################
# Copyright (C) 2013, Frank Sauerburger
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
###############################################################################
# Usage
#
# qlatex [-o] file1 [file2 [file3 ... ]]
#
###############################################################################

import sys
import os

def parsePackages(lines):
  for i in range(0, len(lines)):
    if lines[i].strip() == "":
      break
  packages = lines[:i]
  del lines[:i]
  ps = ""
  for p in packages:
    ps += p  
  return ps

def makeLatex(fname):
  title    = ""
  content  = ""
  author   = ""
  packages = ""

  f = open(fname, "r")
  lines = f.readlines()
  if lines[1][0:6] == "="*6:
    title = lines[0].strip()
    del lines[0:2]
    if lines[0].strip() != "":
      packages = parsePackages(lines)

  if lines[2][0:6] == "="*6:
    title = lines[0].strip()
    author = lines[1].strip()
    del lines[0:3]
    if lines[0].strip() != "":
      packages = parsePackages(lines)

  for line in lines:
    if line[0:3] == "===":
      content += "\section{" + line[3:].strip() + "}\n"
      continue
    if line[0:2] == "==":
      content += "\subsection{" + line[2:].strip() + "}\n"
      continue
    if line[0:1] == "=":
      content += "\subsubsection{" + line[1:].strip() + "}\n"
      continue
    content += line
    
  f.close()
  
  tpl = open(os.path.expanduser("~/.qlatex.tex"), "r")
  tpl = tpl.readlines()

  output = [x.replace("%%%TITLE%%%", title).replace("%%%CONTENT%%%", content).replace("%%%AUTHOR%%%", author).replace("%%%PACKAGES%%%", packages) for x in tpl]

  f = open(fname, "w");
  f.writelines(output)
  f.close()

def makePdf(fname):
  pdf = os.popen("pdflatex " + fname);
  for l in pdf:
    print(l.strip()) 
  
def openPdf(fname):
  os.popen("evince " + fname[:-4] + ".pdf");

if __name__ == "__main__":
  show = False
  if sys.argv[1] == "-o":
    show = True
    del sys.argv[1]

  for arg in sys.argv[1:]:
    makeLatex(arg)
    makePdf(arg)
    if show: openPdf(arg)
